l0=[]
print("Origimal list:",l0)
print("Adding elements")
l0.append(2)
l0.append(8)
l0.append(9)
l0.append(7)
print(l0)
print("Extend:")
l0.extend([3,4,5])
print(l0)
print("Deleting the element")
print("remove() -deletes a particular element")
l0.remove(5)
print(l0)
print("pop-deletes the last element")
print(l0.pop())
print("After deleting the last element")
print(l0)
print("Final list")
print(l0)
